### openwisp2
## tasks
- name: 'install python'
  raw: sudo apt-get -y install python

- name: 'install python2'
  raw: sudo apt-get -y install python-simplejson

##For older Ubuntu systems
- name: 'install aptitude'
  raw: sudo apt-get -y install aptitude

- import_tasks: variables.yml
  tags: [openwisp2, variables]

- import_tasks: apt.yml
  tags: [openwisp2, apt]
  when: ansible_os_family == 'Debian'

- import_tasks: yum.yml
  tags: [openwisp2, yum]
  when: ansible_os_family == 'RedHat'

- import_tasks: pip.yml
  tags: [openwisp2, pip]

# comprises django_secret_key.yml
- import_tasks: django.yml
  tags: [openwisp2, django]

- import_tasks: firewalld.yml
  tags: [openwisp2, firewalld]
  when: ansible_os_family == 'RedHat'

- import_tasks: selinux.yml
  tags: [openwisp2, selinux]
  when: ansible_os_family == 'RedHat'

- import_tasks: supervisor.yml
  tags: [openwisp2, supervisor]

- import_tasks: nginx.yml
  tags: [openwisp2, nginx]

- import_tasks: cron.yml
  tags: [openwisp2, cron]

- import_tasks: complete.yml
  tags: [openwisp2]
